spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortner
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Kv139@postgres
  jpa:
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
